apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: api
  name: api
  namespace: antx
spec:
  selector:
    matchLabels:
      app: api
  replicas: 1
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api
        imagePullPolicy: Never
        image: localhost:5000/backend:latest
        command:
        - /bin/bash
        - -c
        args:
        - fastapi api.py
        resources:
          request:
            cpu: 500m
            memory: 528M
          limit:
            cpu: 1
            memory: 1Gi
        env:
          - name: READ_BUCKET
            value: "###ZARF_VAR_S3_READ_BUCKET_NAME###"
          - name: WRITE_BUCKET
            value: "###ZARF_VAR_S3_WRITE_BUCKET_NAME###"
          - name: VALKEY_HOST
            value: "###ZARF_VAR_VALKEY_HOST###"
          - name: VALKEY_PASSWORD
            value: "###ZARF_VAR_VALKEY_PASSWORD###"
          - name: VALKEY_PORT
            value: "###ZARF_VAR_VALKEY_PORT###"
        resources: {}